name: CI (Windows)

on:
  push: { branches: [ master ] }
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with: { node-version: 12.x }
    - name: Install esy
      run: npm install -g esy

    - name: Setup dependencies
      run: |
        cp doc/esy.windows.json esy.json
        rm src/github/unix/dune
        esy i

    - name: Build
      run: esy b
